version: "$(appveyor_repo_branch).{build}"

branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - ps: .\Build\Setup-Build-Environment.ps1

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(pactnet_assembly_version).{build}"
  assembly_file_version: "$(pactnet_assembly_version).{build}"
  assembly_informational_version: "{version}"

deploy:
  - provider: NuGet
    skip_symbols: true
    api_key:
      secure: Vlw7m7mXEZ9XqlZBsQ4fzqDKjO8yTdtXhO9c04RnrD4zwhf6dx+lxBmC9TJ7EF6G
    on:
      branch: master
      appveyor_repo_tag: true

artifacts:
  - path: '**\Build\PactNet*.nupkg'
  - path: '**\Build\coverage\*'

configuration: Release

build:
  project: PactNet.sln
  verbosity: normal
  on:
    branch: master

before_build:
  - nuget restore

after_build:
  - ps: .\Build\Publish-Release.ps1 -ReleaseVersionNumber "$env:PACTNET_VERSION"

after_test:
  - ps: .\Build\Tests-Coverage.ps1 -GenerateSummaryReport