version: 0.1.4-beta.{build}

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.4.{build}"
  assembly_file_version: "0.1.4.{build}"
  assembly_informational_version: "{version}"
  
deploy:
  - provider: NuGet
    skip_symbols: true
    api_key:
      secure: Vlw7m7mXEZ9XqlZBsQ4fzqDKjO8yTdtXhO9c04RnrD4zwhf6dx+lxBmC9TJ7EF6G
    on:
      branch: master
      appveyor_repo_tag: true

artifacts:
  - path: '**\PactNet*.nupkg'

configuration: Release

build:
  project: PactNet.sln
  verbosity: normal
  on:
    branch: master

after_build:
  - .\Build\Publish-Release.ps1 -ReleaseVersionNumber 0.1.4-beta